vault:
  clusterSecretStoreName: vault-backend
clusterset:
  name: clusterset1
  clusters:
  # - name: cluster1
  #   provider: gcp
  #   clusterGroupLabel: region-one
  #   tokenPath: secret/hub/gcp-cluster
  #   serverPath: secret/hub/gcp-cluster
  #   cloudCredentialPath: secret/hub/gcp-credentials
  # - name: cluster2
  #   provider: aws
  #   clusterGroupLabel: region-two
  #   tokenPath: secret/hub/aws-cluster
  #   serverPath: secret/hub/aws-cluster
  #   instanceType: c5d.large
  #   cloudCredentialPath: secret/hub/aws-credentials
