apiVersion: batch/v1
kind: Job
metadata:
  name: region-configmap
spec:
  template:
    spec:
      serviceAccountName: create-certs-service-account
      containers:
      - name: region-configmap
        image: 'bitnami/kubectl'
        command:
          - sh
          - -c
          - |
            echo "Getting region \n"
            REGION=$(kubectl cluster-info dump | grep topology.kubernetes.io/region | awk 'FNR == 1 { print $2}' | tr -d '\",')
            echo "Region=$REGION\n"

            echo "Getting zone \n"
            ZONE=$(kubectl cluster-info dump | grep topology.kubernetes.io/zone | awk 'FNR == 1 { print $2}' | tr -d '\",')
            echo "Zone=$ZONE\n"

            kubectl create configmap region-zone-config --from-literal=region=$REGION --from-literal=zone=$ZONE

      restartPolicy: Never
  backoffLimit: 4
