---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: create-certs-service-account
  namespace:  {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: create-certs-role
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - secrets
      - pods
      - serviceaccounts
      - Role
      - RoleBinding
      - nodes
      - configmaps
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: create-certs-rolebinding
  namespace: {{ .Release.Namespace }} 
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: create-certs-role
subjects:
- namespace: {{ .Release.Namespace }} 
  kind: ServiceAccount
  name: create-certs-service-account
---
apiVersion: v1
kind: Pod
metadata:
  name: create-certs
spec:
  serviceAccountName: create-certs-service-account
  initContainers:
  - name: create-ca-cert
    terminationMessagePath: /dev/termination-log
    resources: {}
    imagePullPolicy: Always
    volumeMounts:
      - name: certs-volume
        mountPath: /var/run/secrets/certs
      - name: my-safe-directory-volume
        mountPath: /var/run/secrets/my-safe-directory
    terminationMessagePolicy: File
    image: 'cockroachdb/cockroach'
    command:
      - sh
      - -c
      - |
        echo "Creating certs in the directory /var/run/secrets/"
        cockroach cert create-ca --certs-dir=/var/run/secrets/certs --ca-key=/var/run/secrets/my-safe-directory/ca.key
        cockroach cert create-client root --certs-dir=/var/run/secrets/certs --ca-key=/var/run/secrets/my-safe-directory/ca.key
        chmod 640 /var/run/secrets/certs/*.*
        chmod 640 /var/run/secrets/my-safe-directory/*.*
        echo " certs directory "
        ls -al /var/run/secrets/certs
        echo " safe directory "
        ls -al /var/run/secrets/my-safe-directory
        echo "Finished creating certs"
  
  - name: create-ca-secret
    terminationMessagePath: /dev/termination-log
    resources: {}
    imagePullPolicy: Always
    volumeMounts:
      - name: certs-volume
        mountPath: /var/run/secrets/certs
      - name: my-safe-directory-volume
        mountPath: /var/run/secrets/my-safe-directory
    terminationMessagePolicy: File
    image: 'openshift/origin-cli'
    command:
      - sh
      - -c
      - |
        oc delete secret cockroachdb.client.root || true
        oc delete secret cockroachdb.node || true
        oc create secret generic cockroachdb.client.root --from-file=/var/run/secrets/certs --namespace {{ .Release.Namespace }}

  - name: create-node-cert
    terminationMessagePath: /dev/termination-log
    resources: {}
    imagePullPolicy: Always
    volumeMounts:
      - name: certs-volume
        mountPath: /var/run/secrets/certs
      - name: my-safe-directory-volume
        mountPath: /var/run/secrets/my-safe-directory
    terminationMessagePolicy: File
    image: 'cockroachdb/cockroach:v22.1.6'
    command:
      - sh
      - -c
      - |
        cockroach cert create-node localhost 127.0.0.1 cockroachdb-public cockroachdb-public.{{ .Release.Namespace }} cockroachdb-public.{{ .Release.Namespace }}.svc.cluster.local "*.cockroachdb" "*.cockroachdb.{{ .Release.Namespace }}" "*.cockroachdb.{{ .Release.Namespace }}.svc.cluster.local" --certs-dir=/var/run/secrets/certs --ca-key=/var/run/secrets/my-safe-directory/ca.key
  
  - name: create-node-secret
    terminationMessagePath: /dev/termination-log
    resources: {}
    imagePullPolicy: Always
    volumeMounts:
      - name: certs-volume
        mountPath: /var/run/secrets/certs
      - name: my-safe-directory-volume
        mountPath: /var/run/secrets/my-safe-directory
    terminationMessagePolicy: File
    image: 'openshift/origin-cli'
    command:
      - sh
      - -c
      - |
        oc create secret generic cockroachdb.node --from-file=/var/run/secrets/certs --namespace {{ .Release.Namespace }}
  restartPolicy: Never 
  containers:
  - command:
      - sh
      - -c
      - |
        sleep 20
    image: 'openshift/origin-cli'
    name: create-certs
  terminationGracePeriodSeconds: 5
  volumes:
    - name: certs-volume
      emptyDir: {}
    - name: my-safe-directory-volume
      emptyDir: {}