apiVersion: v1
kind: Pod
metadata:
  name: create-certs
spec:
  serviceAccountName: cockroachdb
  initContainers:
  - name: create-ca-cert
    terminationMessagePath: /dev/termination-log
    resources: {}
    imagePullPolicy: Always
    volumeMounts:
      - name: certs-volume
        mountPath: /var/run/secrets/certs
      - name: my-safe-directory-volume
        mountPath: /var/run/secrets/my-safe-directory
    terminationMessagePolicy: File
    image: 'cockroachdb/cockroach'
    command:
      - sh
      - -c
      - |
        echo "Creating certs in the directory /var/run/secrets/"
        cockroach cert create-ca --certs-dir=/var/run/secrets/certs --ca-key=/var/run/secrets/my-safe-directory/ca.key
        cockroach cert create-client root --certs-dir=/var/run/secrets/certs --ca-key=/var/run/secrets/my-safe-directory/ca.key
        chmod 644 /var/run/secrets/certs/*.*
        chmod 644 /var/run/secrets/my-safe-directory/*.*
        echo " certs directory "
        ls -al /var/run/secrets/certs
        echo " safe directory "
        ls -al /var/run/secrets/my-safe-directory
        echo "Finished creating certs"
  
  - name: create-ca-secret
    terminationMessagePath: /dev/termination-log
    resources: {}
    imagePullPolicy: Always
    volumeMounts:
      - name: certs-volume
        mountPath: /var/run/secrets/certs
      - name: my-safe-directory-volume
        mountPath: /var/run/secrets/my-safe-directory
    terminationMessagePolicy: File
    image: 'openshift/origin-cli'
    command:
      - sh
      - -c
      - |
        oc create secret generic cockroachdb.client.root --from-file=/var/run/secrets/certs --namespace {{ .Release.Namespace }}

  - name: create-node-cert
    terminationMessagePath: /dev/termination-log
    resources: {}
    imagePullPolicy: Always
    volumeMounts:
      - name: certs-volume
        mountPath: /var/run/secrets/certs
      - name: my-safe-directory-volume
        mountPath: /var/run/secrets/my-safe-directory
    terminationMessagePolicy: File
    image: 'cockroachdb/cockroach:v22.1.6'
    command:
      - sh
      - -c
      - |
        cockroach cert create-node localhost 127.0.0.1 cockroachdb-public cockroachdb-public.{{ .Release.Namespace }} cockroachdb-public.{{ .Release.Namespace }}.svc.cluster.local "*.cockroachdb" "*.cockroachdb.{{ .Release.Namespace }}" "*.cockroachdb.{{ .Release.Namespace }}.svc.cluster.local" --certs-dir=/var/run/secrets/certs --ca-key=/var/run/secrets/my-safe-directory/ca.key
  
  - name: create-node-secret
    terminationMessagePath: /dev/termination-log
    resources: {}
    imagePullPolicy: Always
    volumeMounts:
      - name: certs-volume
        mountPath: /var/run/secrets/certs
      - name: my-safe-directory-volume
        mountPath: /var/run/secrets/my-safe-directory
    terminationMessagePolicy: File
    image: 'openshift/origin-cli'
    command:
      - sh
      - -c
      - |
        oc create secret generic cockroachdb.node --from-file=certs --namespace {{ .Release.Namespace }}
        
  containers:
  - command:
      - sleep
      - "120"
    image: busybox
    name: create-certs
  terminationGracePeriodSeconds: 5
  volumes:
    - name: certs-volume
      emptyDir: {}
    - name: my-safe-directory-volume
      emptyDir: {}