---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ManagedClusterSet
metadata:
  name: "{{ .Values.clusterset.name }}"
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrole1
rules:
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["managedclustersets/join"]
    resourceNames: ["{{ .Values.clusterset.name }}"]
    verbs: ["create"]

{{- $clustersetName := $.Values.clusterset.name }}
{{- range $.Values.clusterset.clusters }}
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: "{{ .name }}"
  labels:
    cluster.open-cluster-management.io/clusterset: "{{ $clustersetName }}"
spec:
  hubAcceptsClient: true
{{- end }}
