{{- $clustersetName := $.Values.clusterset.name }}
{{- $clusterSecretStoreName := $.Values.vault.clusterSecretStoreName }}
{{- range $.Values.clusterset.clusters }}
---
apiVersion: addon.open-cluster-management.io/v1alpha1
kind: ManagedClusterAddOn
metadata:
  name: submariner
  namespace:  {{ .name }}
spec:
  installNamespace: submariner-operator
{{ if eq .provider "aws" }}
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .name }}-aws-creds
  namespace: {{ .name }}
spec:
  secretStoreRef:
    name: "{{ $clusterSecretStoreName }}"
    kind: ClusterSecretStore
  target:
    name: {{ .name }}-aws-creds
    creationPolicy: Owner
  data:
  - secretKey: aws_access_key_id
    remoteRef:
      key: {{ .cloudCredentialPath }}
      property: aws_access_key_id
  - secretKey: aws_secret_access_key
    remoteRef:
      key: {{ .cloudCredentialPath }}
      property: aws_secret_access_key
---
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
  name: submariner
  namespace:  {{ .name }}
spec:
  gatewayConfig:
    gateways: 1
    aws:
      instanceType: {{ .instanceType }}
  IPSecNATTPort: 4500
  NATTEnable: true
  cableDriver: libreswan
  credentialsSecret:
    name: {{ .name }}-aws-creds
{{ end }}

{{ if eq .provider "gcloud" }}
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: {{ .name }}-aws-creds
  namespace: {{ .name }}
spec:
  secretStoreRef:
    name: "{{ $clusterSecretStoreName }}"
    kind: ClusterSecretStore
  target:
    name: {{ .name }}-aws-creds
    creationPolicy: Owner
  data:
  - secretKey: osServiceAccount.json
    remoteRef:
      key: {{ .cloudCredentialPath }}
      property: osServiceAccount.json
---
apiVersion: submarineraddon.open-cluster-management.io/v1alpha1
kind: SubmarinerConfig
metadata:
  name: submariner
  namespace: {{ .name }}
spec:
  gatewayConfig:
    gateways: 1
  IPSecNATTPort: 4500
  NATTEnable: true
  cableDriver: libreswan
  credentialsSecret:
    name: {{ .name }}-gcp-creds
{{- end }}
{{- end }}
---
apiVersion: submariner.io/v1alpha1
kind: Broker
metadata:
  name: submariner-broker
  namespace: submariner-broker
spec:
  globalnetEnabled: false
