{{- if .Values.clusterGroup.autoImport }}
---
apiVersion: cluster.open-cluster-management.io/v1alpha1
kind: ManagedClusterSet
metadata:
  name: {{ .Values.clusterGroup.name }}
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: clusterrole1
rules:
  - apiGroups: ["cluster.open-cluster-management.io"]
    resources: ["managedclustersets/join"]
    resourceNames: ["{{ .Values.clusterGroup.name }}"]
    verbs: ["create"]

{{- $clustersetName := $.Values.clusterGroup.name }}
{{- $clusterSecretStoreName := $.Values.global.vault.secretStoreName }}
{{- range .Values.clusterGroup.managedClusterGroups }}
---
apiVersion: cluster.open-cluster-management.io/v1
kind: ManagedCluster
metadata:
  name: {{ .name }}
  labels:
    name: {{ .name }}
    cloud: auto-detect
    vendor: auto-detect
    clusterGroup: {{ .name }}
    cluster.open-cluster-management.io/clusterset: "{{ $clustersetName }}"
spec:
  hubAcceptsClient: true
---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: auto-import-secret
  namespace: {{ .name }}
spec:
  secretStoreRef:
    name: "{{ $clusterSecretStoreName }}"
    kind: ClusterSecretStore
  target:
    name: auto-import-secret
    creationPolicy: Owner
  data:
  - secretKey: token
    remoteRef:
      key: secret/{{ $clustersetName }}/{{ .name }}
      property: token
  - secretKey: server
    remoteRef:
      key: secret/{{ $clustersetName }}/{{ .name }}
      property: server
---
apiVersion: agent.open-cluster-management.io/v1
kind: KlusterletAddonConfig
metadata:
  name: {{ .name }}
  namespace: {{ .name }}
spec:
  clusterName: {{ .name }}
  clusterNamespace: {{ .name }}
  clusterLabels:
    name: {{ .name }}
    cloud: auto-detect
    vendor: auto-detect
    clusterGroup: {{ .name }}
    cluster.open-cluster-management.io/clusterset: "{{ $clustersetName }}"
  applicationManager:
    enabled: true
  policyController:
    enabled: true
  searchCollector:
    enabled: true
  certPolicyController:
    enabled: true
  iamPolicyController:
    enabled: true
{{- end }}
{{- end }}

