{{- if .Values.clusterGroup.isHubCluster }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: hub-ca-crt-policy
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: hub-ca-crt
          annotations:
            apps.open-cluster-management.io/deployables: "configmap"
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                kind: ConfigMap
                metadata:
                  name: hub-root-ca.crt
                  namespace: golang-external-secrets
                apiVersion: v1
                data:
                  ca.crt: '{{ `{{hub index (lookup "v1" "ConfigMap" "golang-external-secrets" "kube-root-ca.crt").data "ca.crt" hub}}` }}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: hub-ca-crt-placement-binding
placementRef:
  name: hub-ca-crt-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: hub-ca-crt-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
# We need to run this on any managed cluster but not on the HUB
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: hub-ca-crt-placement
spec:
  # This will go to all clusters
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
{{- end }}