{{- if .Values.clusterGroup.isHubCluster }}
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: golang-external-secrets-policy
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: golang-external-secrets
          annotations:
            apps.open-cluster-management.io/deployables: "secret"
        spec:
          remediationAction: enforce
          severity: medium
          namespaceSelector:
            include:
              - default
          object-templates:
            - complianceType: mustonlyhave
              objectDefinition:
                kind: Secret
                type: Opaque
                metadata:
                  name: vault-token
                  namespace: golang-external-secrets
                apiVersion: v1
                data:
                  token: '{{ `{{hub index (lookup "v1" "Secret" "golang-external-secrets" "golang-external-secrets").data "token" hub}}` }}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: golang-external-secrets-placement-binding
placementRef:
  name: golang-external-secrets-placement
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
  - name: golang-external-secrets-policy
    kind: Policy
    apiGroup: policy.open-cluster-management.io
---
# We need to run this on any managed cluster but not on the HUB
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: golang-external-secrets-placement
spec:
  # This will go to all clusters
  clusterConditions:
    - status: 'True'
      type: ManagedClusterConditionAvailable
{{- end }}