---
apiVersion: external-secrets.io/v1alpha1
kind: ExternalSecret
metadata:
  name: cockroachdb.ca
  namespace: cockroachdb
spec:
  secretStoreRef:
    name: {{ .Values.global.vault.secretStoreName }}
    kind: ClusterSecretStore
  target:
    name: cockroachdb.ca
    creationPolicy: Owner
  data:
  - secretKey: ca.crt
    remoteRef:
      key: secret/{{ .Values.clusterGroup.name }}/cockroachdb-root-ca-crt
      property: content
  - secretKey: ca.key
    remoteRef:
      key: secret/{{ .Values.clusterGroup.name }}/cockroachdb-root-ca-key
      property: content

